name: dcat
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  dio: ^5.7.0
  dotenv: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  rxdart: ^0.28.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
